name: regolith-desktop is installable

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test-ubuntu-amd64:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        stage: [ unstable, testing, release ]
        arch: [ amd64 ]
        distro: [ ubuntu ]
        codename: [ focal, impish, jammy ]
    steps:
      - name: Test Ubuntu 20.04
        uses: kgilmer/test-ubuntu-20.04-action@v1.1.5
        with:
          apt-key-url: https://regolith-linux.github.io/package-repo/regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] https://regolith-${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }}.s3.amazonaws.com ${{ matrix.codename }} main"
          target-package: "regolith-desktop"
  test-ubuntu-arm64:
    runs-on: [self-hosted, Linux, ARM64]
    strategy:
      matrix:
        stage: [ unstable, testing, release ]
        arch: [ arm64 ]
        distro: [ ubuntu ]
        codename: [ focal, impish, jammy ]
    steps:
      - name: Test Ubuntu 20.04
        uses: kgilmer/test-ubuntu-20.04-action@v1.1.5
        with:
          apt-key-url: https://regolith-linux.github.io/package-repo/regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] https://regolith-${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }}.s3.amazonaws.com ${{ matrix.codename }} main"
          target-package: "regolith-desktop"
  test-debian-amd64:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        stage: [ unstable, testing, release ]
        arch: [ amd64 ]
        distro: [ debian ]
        codename: [ bullseye ]
    steps:
      - name: Test Debian Bullseye
        uses: kgilmer/test-debian-bullseye-action@v1
        with:
          apt-key-url: https://regolith-linux.github.io/package-repo/regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] https://regolith-${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }}.s3.amazonaws.com ${{ matrix.codename }} main"
          target-package: "regolith-desktop"
  test-debian-arm64:
    runs-on: [self-hosted, Linux, ARM64]
    strategy:
      matrix:
        stage: [ unstable, testing, release ]
        arch: [ arm64 ]
        distro: [ debian ]
        codename: [ bullseye ]
    steps:
      - name: Test Debian Bullseye
        uses: kgilmer/test-debian-bullseye-action@v1
        with:
          apt-key-url: https://regolith-linux.github.io/package-repo/regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] https://regolith-${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }}.s3.amazonaws.com ${{ matrix.codename }} main"
          target-package: "regolith-desktop"